--ESTRUTURA BÁSICA PL/SQL--
DECLARE
    V_VARIAVEIS VARCHAR2(5);
BEGIN
    SELECT NOME_COLUNA
    INTO V_VARIAVEIS
    FROM NOME_TABELA;
EXCEPTION
    WHEN EXCEPTION_NAME THEN;
END;
/
--DOS INTENS ACIMA APENAS O BEGIN E END SÃO OBRIGATORIOS, OS DEMAIS CASO HAJA ALGUMA EXECEÇÃO OU A NECESSIDADE DE DECLARAR VARIAVEIS--

--ESSE COMANDO JOGA UMA INFORMAÇÃO NA TELA--
DBMS_OUTPUT.PUT_LINE
--DBMS_OUTPUT É UMA BIBLIOTECA DO PL/SQL, VAMOS COLOCAR EM PRÁTICA ABAIXO:--
SET SERVEROUTPUT ON
DECLARE
    V_TESTE VARCHAR2(30) := 'Hello World';
BEGIN
    DBMS_OUTPUT.PUT_LINE(V_TESTE);
END;
/