--TRATAR QUANDO A CONDIÇÃO É VERDADEIRA E DE QUANDO É FALSA--
DECLARE
    V_COL1 TABELA1.COL1%TYPE;
    V_TAMANHO NUMBER(3);
BEGIN
    SELECT LENGTH(COL1), COL1
    INTO V_TAMANHO, V_COL1
    FROM TABELA1;
    
    IF V_TAMANHO > 25 THEN
        DBMS_OUTPUT.PUT_LINE('Texto = ' || V_COL1);
    ELSE
        DBMS_OUTPUT.PUT_LINE('Texto menor ou igual a 25');
    END IF;
END;
/

--DEIXANDO O ELSE APRESENTAR ESSES DADOS--
UPDATE TABELA1 SET COL1 = '12345';

--DEIXANDO O IF THEN APRESENTAR ESSES DADOS--
UPDATE TABELA1 SET COL1 = '123456789123456789123456789'
