SET SERVEROUTPUT ON
--APLICANDO ESTRUTURAS DE IF THEN--
DECLARE
    V_COL1 TABELA1.COL1%TYPE;
    V_TAMANHO NUMBER(3);
BEGIN 
--USAMOS O LENGTH QUANDO QUEREMOS SABER O VALOR EM NUMERO DO DADO CONTIDO NA COLUNA--
    SELECT LENGTH(COL1), COL1
    INTO V_TAMANHO, V_COL1
    FROM TABELA1;
--CONDICIONAL PARA JOGAR A INFORMAÇÃO NA TELA, CASO OQUE ESTÁ ARMAZINADO NA COL1 FOR MAIOR QUE 25 DEVE SER MOSTRADO, COMO SABEMOS QUE POSSUI 30 CARACTERES, SERÁ APRESENTADO SEM ERROS--
    IF V_TAMANHO > 25 THEN
        DBMS_OUTPUT.PUT_LINE ('Texto = ' || V_COL1);
    END IF;
END;
/
