--PARA RECUPERAR DROP, PRIMEIRO ULTILIZAMOS ESSE COMANDO QUE VERIFICA SE PELA AINDA ESTÁ NA "LIXEIRA"--
SHOW RECYCLEBIN;

--CASO SIM ULTILIZE ESSE CODIGO ABAIXO--
FLASHBACK TABLE nome_tabela TO BEFORE DROP;
