--CRIAR UMA VIEW CHAMADA VW_PROFISSOES QUE REALIZA UMA CONSULTA NA TABELA CLIENTE AGRUPANDO PELA PROFISSAO DOS CLIENTES--
--TRAGA O NOME DA PROFISSAO E A QUANTIDADE DE CLIENTES QUE A DECLARAM, ULTILZIANDO APELIDOS NAS COLUNAS--
--TRAZER APENAS PROFISSOES QUE POSSUAM 10 PESSOAS OU MAIS--
--ORDENAR DAS PROFISSOES MAIS POPULARES PARA AS MENOS POPULARES--
CREATE VIEW VW_PROFISSOES AS
SELECT DS_CLIENTE_PROFISSAO "PROFISSAO", COUNT(*) "QUANTIDADE"
FROM TB_CLIENTE
GROUP BY DS_CLIENTE_PROFISSAO
HAVING COUNT(*) >= 10
ORDER BY COUNT(*) DESC;

--QUANDO SE CRIA UMA VIEW ELA FUNCIONA COMO SE FOSSE UMA CONSULTA QUE CONSEGUE PUXAR SEMPRE QUE QUISER, UMA VEZ JÁ CRIADA CONFORME ACIMA PODEMOS CONSULTAR USANDO--
SELECT * FROM VW_PROFISSOES;

--PARA APAGAR A VIEW BASTA ULTILIZAR UM DROP CONVENCIONAL--
DROP VIEW VW_PROFISSOES;

--UM OUTRO EXEMPLO, CRIAR UMA VIEW CHAMADA VW_ACUMULADO_2015 QUE REALIZA UMA CONSULTA TRAZENDO O MES E O VALOR TOTAL EM HOSPEDAGENS--
--ULITLIZE A DATA DE INICIO DE HOSPEDAGEM COMO REFERENCIA, E TRAGA SOMENTE VALORES DO ANO DE 2015--
--ULTILIZAR APELIDOS NAS COLUNAS E ORDENAR O MES MAIS RENTAVEL PARA O MENOS RENTAVEL--
CREATE VIEW VW_ACUMULADO_2015 AS
SELECT TO_CHAR(DT_HOSPEDAGEM_INICIO, 'MON') "MêS", SUM(VL_HOSPEDAGEM) "VALOR"
FROM TB_HOSPEDAGEM
WHERE DT_HOSPEDAGEM_INICIO >= '01-JAN-2015'
GROUP BY TO_CHAR(DT_HOSPEDAGEM_INICIO, 'MON')
ORDER BY SUM(VL_HOSPEDAGEM)DESC;

SELECT * FROM VW_ACUMULADO_2015;

--OUTRO EXEMPLO, CRIAR UMA VIEW QUE DEVERÁ TRAZER O NOME DOS CLIENTES QUE NÃO POSSUEM NENHUMA HOSPEDAGEM ASSOCIADA Á ELES--
--ULTILIZAR APELIDOS PARA AS COLUNAS E ORDENAR PELO NOME DO CLIENTE EM ORDEM ALFABETICA--
CREATE VIEW VW_NAO_CLIENTES AS
SELECT NM_CLIENTE "NOME CLIENTE"
FROM TB_CLIENTE
WHERE CD_CLIENTE NOT IN (SELECT DISTINCT CD_CLIENTE FROM TB_HOSPEDAGEM);

SELECT * FROM VW_NAO_CLIENTES;

DELETE FROM TB_HOSPEDAGEM WHERE CD_CLIENTE = 100;
